### ISSUE TITLE
Enhance linux check for empty keystore folder

### ISSUE THREAD

**Issue by aitseitz** [Alfresco/alfresco-ssl-generator#15]
**Situation:**
The current run.sh script checks in line
https://github.com/Alfresco/alfresco-ssl-generator/blob/master/ssl-tool/run.sh#L122
if the target folder for generated keystores is not empty...in case it is not empty it skips further keystore generation...

```
if [ "$(ls $KEYSTORES_DIR)" ]; then   
 echo "Keystores folder is not empty, skipping generation process..."    
 exit 1 
fi
```

This works perfectly on the system I've tested it, but can have some tricky side effects....
The `ls` command is an alias in most linux distributions. This can lead to an unexpected behavior in certain environments when the ls commands is an alias for `$ ls -al` and list as well the `.` and `..`` folders. 

**Solution:**
To prevent this in my opinion we have two options:

a) check if KEYSTORES_DIR is a directory
```
 if [ -d $KEYSTORES_DIR ]; then
   echo "Keystores folder is not empty, skipping generation process..."    
   exit 1 
 fi
```

b) make sure the ls command list the directory content without `.` and ``..``
```
if [ "$(ls -A $KEYSTORES_DIR)" ]; then   
   echo "Keystores folder is not empty, skipping generation process..."    
   exit 1 
 fi
```
from ls man pages:
-A, --almost-all
              do not list implied . and ..

@aborroy:
As requested, I'll prepare an PullRequest for the b) solution with the ls -A parameter.
For final review, please execute your script via ansible and make sure the std error is not thrown on the environment where ls is an alias for ls -al:

```
- name: "Generate new Keystores on Host if keystore folder does not exist"
      ansible.builtin.shell:
        cmd: "{{ acs_home }}/alfresco-ssl-generator/ssl-tool/run.sh -keysize 2048 -alfrescoversion enterprise -alfrescoformat classic"
        chdir: "{{ acs_home }}/alfresco-ssl-generator/ssl-tool/"
        creates: "{{ acs_home }}/alfresco-ssl-generator/ssl-tool/keystores"
      register: keystore_generated
      when: not acs_keystore_folder.stat.exists | bool
      tags:
        - keystore
```
